# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-09 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=200)),
                ('pnr', models.CharField(max_length=200)),
                ('delivery_station_code', models.CharField(max_length=200)),
                ('train_number', models.CharField(max_length=200)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
